### ISSUE TITLE
Require review on entity model

### ISSUE THREAD

**Issue by cedar-technologies** [skalpel-tech/ldtscrm#90]
should that be typeId ?

https://github.com/skalpel-tech/ldtscrm/blob/3c3fb92d00dde1a736c95d2d63ee3b9c595f55af/app/core/entity/models.py#L53

**Comment by eugene-p** [comment]
I think should be entityTypeId. Will fix as soon as get home

**Comment by cedar-technologies** [comment]
Yup, thanks!

**Comment by cedar-technologies** [comment]
fixed
